module.exports = [
    { type: "Emoji Clue", clue: "💪🏽🙎🏽‍♂️💔👨‍🦲💥🏹", correct: "Baahubali", alternates: ["Bahubali", "Baahubali: The Beginning", "Baahubali The Conclusion"] },
    { type: "Emoji Clue", clue: "🚂💞👧🏻🧔🏻", correct: "Dilwale Dulhania Le Jayenge", alternates: ["DDLJ"] },
    { type: "Emoji Clue", clue: "👨‍🏫🛸👽", correct: "Koi Mil Gaya", alternates: ["Koi... Mil Gaya"] },
    { type: "Emoji Clue", clue: "🐯🛣️🏃‍♂️", correct: "Ek Tha Tiger", alternates: [] },
    { type: "Emoji Clue", clue: "🥊👩🏽‍🦱🏆", correct: "Mary Kom", alternates: [] },
    { type: "Emoji Clue", clue: "👧🏽🐐🧕🏼🇵🇰", correct: "Bajrangi Bhaijaan", alternates: [] },
    { type: "Emoji Clue", clue: "👑🐎⚔️🛡️", correct: "Padmaavat", alternates: ["Padmavati"] },
    { type: "Emoji Clue", clue: "👮‍♂️💪🦁", correct: "Singham", alternates: [] },
    { type: "Emoji Clue", clue: "🤓🤖🔥", correct: "Robot", alternates: ["Enthiran"] },
    { type: "Emoji Clue", clue: "🪓🩸🐕👨‍👦", correct: "Animal", alternates: [] },
    { type: "Dialogue", clue: `"Pushpa, Pushpa Raj... Main jhukega nahi."`, correct: "Pushpa", alternates: ["Pushpa: The Rise"] },
    { type: "Dialogue", clue: `"Kitne aadmi the?"`, correct: "Sholay", alternates: [] },
    { type: "Dialogue", clue: `"Bade bade deshon mein aisi choti choti baatein hoti rehti hai."`, correct: "Dilwale Dulhania Le Jayenge", alternates: ["DDLJ"] },
    { type: "Dialogue", clue: `"Picture abhi baaki hai mere dost!"`, correct: "Om Shanti Om", alternates: ["OSO"] },
    { type: "Dialogue", clue: `"Don ko pakadna mushkil hi nahi, namumkin hai."`, correct: "Don", alternates: [] },
    { type: "Dialogue", clue: `"Ek chutki sindoor ki keemat, tum kya jano Ramesh babu?"`, correct: "Om Shanti Om", alternates: ["OSO"] },
    { type: "Dialogue", clue: `"How's the josh? High Sir!"`, correct: "Uri", alternates: ["Uri: The Surgical Strike"] },
    { type: "Dialogue", clue: `"Amarendra Baahubali yani main..."`, correct: "Baahubali", alternates: ["Baahubali 2", "Bahubali"] },
    { type: "Song Lyrics", clue: `"Tujhe dekha toh yeh jaana sanam..."`, correct: "Dilwale Dulhania Le Jayenge", alternates: ["DDLJ"] },
    { type: "Song Lyrics", clue: `"Why this Kolaveri Kolaveri Kolaveri di?"`, correct: "3", alternates: ["Moonu"] },
    { type: "Song Lyrics", clue: `"Chhaiya Chhaiya..." (Dancing on a train)`, correct: "Dil Se", alternates: [] },
    { type: "Song Lyrics", clue: `"Naatu Naatu..."`, correct: "RRR", alternates: [] },
    { type: "Song Lyrics", clue: `"Tumhi ho bandhu, sakha tumhi..."`, correct: "Cocktail", alternates: [] },
    { type: "Song Lyrics", clue: `"Apna Time Aayega!"`, correct: "Gully Boy", alternates: [] }
  ];
